### ISSUE TITLE
解码器的输入为回复去掉end_id

### ISSUE THREAD

**Issue by Guaguago** [Kirito0918/cvae-dialog#3]
`# 解码器的输入为回复去掉end_id`
`decoder_inputs = embed_responses[:, :-1, :].transpose(0, 1)  # [seq-1, batch, embed_size]`
您好，您注释写的是去掉end_id,但代码这里是把sequence的最后一个去掉了，但end_id不一定是最后一个。是不是这里有问题？

**Comment by Kirito0918** [comment]
一个batch里最长的那个序列的长度-1是循环的次数, 分割后是每次循环的输入. 因为解码器是通过start_id-&gt;预测真实回复的第一个单词, 到最后一个单词(假设是".")-&gt;预测end_id. 所以最后的end_id没必要输入到解码器. 于是这里就截到了倒数第1个单词. 对于其它比最长的句子短的句子, 其实在计算损失时通过mask忽略掉了,&nbsp; 这里就只是为了少循环一次. 我写的注释可能有些问题, 有些歧义, 但是代码应该没有问题.&nbsp;发送&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenxu05037"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 下午4:00
收件人: "Kirito0918/cvae-dialog"<cvae-dialog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Kirito0918/cvae-dialog] 解码器的输入为回复去掉end_id (#3)





 
# 解码器的输入为回复去掉end_id decoder_inputs = embed_responses[:, :-1, :].transpose(0, 1)  # [seq-1, batch, embed_size]
 您好，您注释写的是去掉end_id,但代码这里是把sequence的最后一个去掉了，但end_id不一定是最后一个。是不是这里有问题？

**Comment by Guaguago** [comment]
OK get it 3Q~
